encyclopedia/urls.py
from cmath import e
from django.urls import path
from django.urls import re_path

from . import views



urlpatterns = [
    path("wiki", views.index, name="index"),
    path("wiki/newpage", views.newPage, name = "newPage"),
    path("wiki/random", views.randomPage, name="randomPage"),
    path("wiki/<str:entryName>", views.getEntry, name="getEntry"),
    path("wiki/<str:editEntryName>/edit", views.editEntry, name="editEntry")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import random
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.shortcuts import render
from re import search
from django.contrib import messages
import markdown2

from . import util

class NewEntryForm(forms.Form):
    entryName = forms.CharField(label="New Entry Name")
    entryContent = forms.CharField(label="New Entry Content", help_text="", widget=forms.Textarea())


def index(request):
    if request.method == "GET" and 'q' in request.GET:
        entryName = request.GET["q"]
        entry = util.get_entry(entryName) 
        if entry:
            entry_htm = markdown2.markdown(entry)
            return render(request, "encyclopedia/entry.html", {
            "entryName": entryName,
            "entry_content": entry_htm
            })
        else:
            list = util.list_entries()
            res = []
            for word in list:
                temp = word.lower()
                if search(entryName, temp):
                    res.append(word)
            if res:        
                return render(request, "encyclopedia/search.html", {
                "results": res
                })
            else:
                return HttpResponse("There's no entry matching your search query :(")
    else:
        return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
        })



def getEntry(request, entryName):
    entry = util.get_entry(entryName)
    if entry:
        entry_htm = markdown2.markdown(entry)
        return render(request, "encyclopedia/entry.html", {
            "entryName": entryName,
            "entry_content": entry_htm
        })
    else:
        return render(request, "encyclopedia/error.html")

def editEntry(request, editEntryName):
    if request.method == 'POST':
        form = NewEntryForm(request.POST)
        if form.is_valid():
            entry_name = form.cleaned_data["entryName"]
            entry_content = form.cleaned_data["entryContent"]
            entry_htm = markdown2.markdown(entry_content)
            util.save_entry(entry_name, entry_content)
            return render(request, "encyclopedia/entry.html", {
            "entryName": entry_name,
            "entry_content": entry_htm
            })
        else:
            messages.error(request, "Invalid Form Data")
            return render(request, "encyclopedia/newpage.html", {
                    "form" : form,
                    "enName" : editEntryName
                })
    else: 
        editEntry = util.get_entry(editEntryName)
        form = NewEntryForm(initial={'entryName' : editEntryName, 'entryContent': editEntry })
        return render(request, "encyclopedia/editpage.html", {
        "form" : form,
        "enName" : editEntryName
        })
    

def newPage(request):
    if request.method == 'POST':
        form = NewEntryForm(request.POST)
        if form.is_valid():
            list = util.list_entries()
            entry_name = form.cleaned_data["entryName"]
            entry_content = form.cleaned_data["entryContent"]
            if entry_name not in list:
                util.save_entry(entry_name, entry_content)
                return HttpResponseRedirect(reverse("getEntry", kwargs={'entryName':entry_name}))
            else:
                messages.error(request, "Entry already in encyclopedia.")
                return render(request, "encyclopedia/newpage.html", {
                    "form" : form
                })
    else:    
        return render(request, "encyclopedia/newpage.html", {
        "form" : NewEntryForm()
        })
    
def randomPage(request):
    list = util.list_entries()
    randEntry = random.choice(list)
    randEntry_cont = util.get_entry(randEntry)
    rand_htm = markdown2.markdown(randEntry_cont)
    return render(request, "encyclopedia/entry.html", {
        "entryName": randEntry,
        "entry_content": rand_htm
    })

encyclopedia/templates/encyclopedia/editpage.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Edit Page</title>
        <style>
            html{
                background: beige;
                padding: 20px;
            }
            #id_entryName{
                display: block;
                width: 300px;
                margin-bottom: 40px;
                height: 30px;
            }
            #id_entryContent{
                display: block;
                width: 900px;
                height: 250px;
                margin-bottom: 40px;
            }
           

        </style>
    </head>
    <body>
        <h1>Edit Page</h1>
        <form action="{% url 'editEntry' editEntryName=enName %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Save Page">
        </form>
    </body>
</html>

encyclopedia/templates/encyclopedia/entry.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{ entryName }}</title>
    </head>
    <body>
        {{ entry_content | safe}}
        <a href="{% url 'editEntry' editEntryName=entryName %}">Edit Page</a>
    </body>
</html>

encyclopedia/templates/encyclopedia/error.html
<!DOCTYPE html>
<html>
    <head>
        <title>404 Error</title>
        <style>
            *{
    transition: all 0.6s;
}

html {
    height: 100%;
}

body{
    font-family: 'Lato', sans-serif;
    color: #888;
    margin: 0;
}

#main{
    display: table;
    width: 100%;
    height: 100vh;
    text-align: center;
}

.fof{
	  display: table-cell;
	  vertical-align: middle;
}

.fof h1{
	  font-size: 50px;
	  display: inline-block;
	  padding-right: 12px;
	  animation: type .5s alternate infinite;
}

@keyframes type{
	  from{box-shadow: inset -3px 0px 0px #888;}
	  to{box-shadow: inset -3px 0px 0px transparent;}
}
        </style>
    </head>
<div id="main">
    <div class="fof">
        <h1>Error 404</h1>
        <p>The page you're looking for doesn't exist:(<p>
    </div>
</div>
</html>

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}


{% block body %}
    <h1>All Pages</h1>
    <ul>
        {% for entry in entries %}
           <li><a href="{% url 'getEntry' entryName=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia" list="entries">
                </form>
                <div>
                    <a href="{% url 'index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'newPage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'randomPage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Create New Page</title>
        <style>
            html{
                background: beige;
                padding: 20px;
            }
            #id_entryName{
                display: block;
                width: 300px;
                margin-bottom: 40px;
                height: 30px;
            }
            #id_entryContent{
                display: block;
                width: 900px;
                height: 250px;
                margin-bottom: 40px;
            }
            
            ul li{
                list-style: none;
                color: red;
                font-size: 18px; 
            }

        </style>
    </head>
    <body>
        <h1> Create New Page</h1>
        <form action="{% url 'newPage' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Save Page">
        </form>
        {% if messages %}
        <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
</ul>
{% endif %}

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Search Results</title>
    </head>
    <body>
        <ul>
            {% for entry in results %}
                <li><a href="{% url 'getEntry' entryName=entry %}">{{ entry }}</a></li>
            {% endfor %}
        </ul>
    </body>
</html>